### ISSUE TITLE
Upon npm run start, fail at index.js, timeout on navToSF

### ISSUE THREAD

**Issue by rochellekwk** [AZn5ReD/saplearninghub-pdf-downloader#12] opened 2020-12-09 23:06 UTC
The following is a section from my terminal, upon running npm run start:

`Submiting...`
`Redirected to: https://accounts.sap.com/saml2/idp/sso`
`Redirected to: https://learninghub.sap.com/saml2/sp/acs/a00026fd2/a00026fd2`
`Connected :)`
`No cookie consent`
`Navigating to SuccessFactor`
`Redirected to: https://learninghub.sap.com/?languagePrompt=true`
`Redirected to: https://performancemanager.successfactors.eu/dpconsent?_s.crb=zly1kgiYRhC26LDUHEWmMYIx8hf5%252fTJSRHiKPS4BD2o%253d`
`Error while navToSF Navigation timeout of 30000 ms exceeded`

Issues may also seem to come from failing at:
* async FrameManager.waitForFrameNavigation
* async f.waitForNavigation
* async W.waitForNavigation

I tried to navigate to https://performancemanager.successfactors.eu/dpconsent?_s.crb=zly1kgiYRhC26LDUHEWmMYIx8hf5%252fTJSRHiKPS4BD2o%253d

![image](https://user-images.githubusercontent.com/37928309/101699391-ef30c180-3adf-11eb-810b-79c517e87a13.png)

The result of npm run start is an empty pdf file.

I am wondering how may I resolve this? Thank you so much @AZn5ReD for your time and patience in looking into this :o

**Comment by AZn5ReD** [comment] 2020-12-10 21:14
Looks like you don't have permission to access to this part of the learning hub. Have you tried to access to the pdf on your browser using the same account ?

**Comment by rochellekwk** [comment] 2020-12-11 02:11
@AZn5ReD Sure, upon clicking "Learning Content" or "Browse Content", I come to this URI: https://saplearninghub.plateau.com/learning/user/deeplink.do?OWASP_CSRFTOKEN=SZAF-0XX4-EU59-2G5L-8IT3-90I9-LZHC-E07D&linkId=HOME_PAGE&fromSF=Y

Which looks like this:
![image](https://user-images.githubusercontent.com/37928309/101852560-d1885880-3bc2-11eb-8f0d-e3b36693258e.png)

And also have access to these eBooks, for example:
![image](https://user-images.githubusercontent.com/37928309/101852681-17452100-3bc3-11eb-9551-dd80b4308472.png)

Thank you so much for your response and looking into this! :D

**Comment by AZn5ReD** [comment] 2020-12-11 19:34
My bad, could you go on "learning content" and make right click and choose "Copy link address" and paste the result in here ?
Thanks

**Comment by rochellekwk** [comment] 2020-12-14 03:34
Sure! Here you go, @AZn5ReD. So sorry for late response!

https://performancemanager.successfactors.eu/sf/learning?Treat-As=WEB&bplte_company=learninghub&_s.crb=xltCMzNVxooYvqWw5E%2fsIT0CFPc%3d

**Comment by rochellekwk** [comment] 2020-12-17 03:20
@AZn5ReD I am wondering if there is a way around this issue? Or it is currently not solvable?

**Comment by devgen** [comment] 2020-12-20 09:44
I got similar issue: 
 Starting script...
(node:11820) [DEP0005] DeprecationWarning: Buffer() is deprecated due to securit
y and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or
Buffer.from() methods instead.
Going to: https://learninghub.sap.com/login
Entering login: ....some value
Entering password: ***
Error during login: waiting for selector "input[id='j_password']" failed: timeou
t 30000ms exceeded


any idea ?

**Comment by FlowerBOII** [comment] 2020-12-24 16:17
@rochellekwk Can you show us what you have in the "DOWNLOAD_URL" part in the config.json file.
I think forgot to change the XXXX part that's why it download an empty pdf file.

**Comment by BobbyG83** [comment] 2020-12-31 12:11
> I got similar issue:
> Starting script...
> (node:11820) [DEP0005] DeprecationWarning: Buffer() is deprecated due to securit
> y and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or
> Buffer.from() methods instead.
> Going to: https://learninghub.sap.com/login
> Entering login: ....some value
> Entering password: ***
> Error during login: waiting for selector "input[id='j_password']" failed: timeou
> t 30000ms exceeded
> 
> any idea ?

Hi,

Yes, this is the issue I'm getting when trying to download an eBook also.

It doesn't seem to have the chance to enter the password.

Thanks

**Comment by AZn5ReD** [comment] 2021-01-09 23:42
Hi,

Can anyone who has the issue send me his/her mail or a way to contact him/her ? I can't reproduce the issue and I would like to try with an other account.

**Comment by redivanov** [comment] 2021-01-15 12:02
Hello. I have the same issue:

![image](https://user-images.githubusercontent.com/53526119/104725153-b8834200-5742-11eb-8535-d12e3e0e6b38.png)

**Comment by redivanov** [comment] 2021-01-15 12:04
Hello!

I have the same issue
![image](https://user-images.githubusercontent.com/53526119/104725289-eb2d3a80-5742-11eb-932d-bf0300eefd8a.png)

**Comment by redivanov** [comment] 2021-01-15 12:06
Hello
I have the same issue
![image](https://user-images.githubusercontent.com/53526119/104725489-38111100-5743-11eb-9f75-562b34424156.png)

**Comment by redivanov** [comment] 2021-01-15 14:03
Made it work at some extent. The idea is to start directly from Success Factors login page:
https://performancemanager.successfactors.eu/login?company=learninghub&loginMethod=PWD
Then make puppeteer to input user/pwd there, hit enter. 
Further script works like a charm, thanks.

**Comment by AZn5ReD** [comment] 2021-01-15 15:07
Thanks for the suggestion, I couldn't make the Success Factor link work before the last release. I'll try to make a new release using it soon.

**Comment by redivanov** [comment] 2021-01-15 15:10
> Thanks for the suggestion, I couldn't make the Success Factor link work before the last release. I'll try to make a new release using it soon.

Thank you for the great script, very helpful

**Comment by AZn5ReD** [comment] 2021-01-15 23:56
Fixed with release 1.1.0

**Closed by AZn5ReD** 2021-01-15 23:56 UTC
